version: '3'

services:

  # --- Databases ---
  # MariaDB
  mariadb:
    image: mariadb:10.6.4-focal
    container_name: "OSVH_MARIADB"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    expose:
      - 3306
      - 33060

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin
    container_name: "OSVH_PHPMYADMIN"
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

  # --- FRONT-END ---
  # Wordpress
  # As the main platform
  wordpress:
    image: wordpress:latest
    container_name: "OSVH_WORDPRESS"
    volumes:
      - wp_data:/var/www/html
    #build:
      #context: /wordpress
      # dockerfile: Dockerfile-wordpress
    restart: always
    ports:
      - 80:80
    environment:
      - .env
    depends_on:
      - mariadb
    links:
      - mariadb

        #  # Moodle
        #  # For the training and competencies
        #
        #  # Discourse
        #  # For the community discussions
        #  # https://github.com/discourse/discourse/blob/main/docs/INSTALL-cloud.md
        #  # https://github.com/discourse/discourse_docker
        #
        #  # --- MANAGEMENT ---
        #
        #  # Portainer
        #  # For managing containers
        #  portainer:
        #    image: portainer/portainer-ce:latest
        #    container_name: "OSVH_PORTAINER"
        #    restart: always
        #    security_opt:
        #      - no-new-privileges:true
        #    volumes:
        #      - /etc/localtime:/etc/localtime:ro
        #      - /var/run/docker.sock:/var/run/docker.sock:ro
        #      - ./portainer-data:/data
        #    ports:
        #      - 9000:9000

volumes:
  mariadb_data:
  wp_data:
