version: '3'

services:

  # --- DATABASE ---
  # MySQL
  db_mysql:
    image: mysql:5.7
    container_name: "OSVH_DB_MYSQL"
    volumes:
      - ./volumes/db_mysql_data:/var/lib/mysql
    restart: always
    env_file:
      - .env_w
    networks:
      - wpsite
  # MariaDB
  db_maria:
    image: mariadb:10.10
    container_name: "OSVH_DB_MARIA"
    volumes:
      - ./volumes/db_maria_data:/var/lib/mysql
    restart: always
    env_file:
      - .env_m
    expose:
      - 3307
      - 33070
    networks:
      - msite
  # PostgreSQL
  db_postgres:
    image: docker.io/postgres:10
    container_name: "OSVH_DB_POSTGRES"
    restart: always
    env_file:
      - .env_l
    expose:
      - 5432
    volumes:
      - ./volumes/db_postgres_data:/var/lib/postgresql
    networks:
      - lsite

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin
    container_name: "OSVH_PHPMYADMIN"
    hostname: platform.villagehosts.eu
    restart: always
    ports:
      - 8086:80
    environment:
      - .env_w
    depends_on:
      - db_mysql
    networks:
      - wpsite


  # --- FRONT-END ---
  # Wordpress
  # As the main platform
  wordpress:
    image: wordpress:latest
    container_name: "OSVH_WORDPRESS"
    hostname: platform.villagehosts.eu
    volumes:
      - ./volumes/wp_data:/var/www/html
    #build:
      #context: /wordpress
      # dockerfile: Dockerfile-wordpress
    restart: always
    ports:
      - 8100:80
    environment:
      - .env_w
    depends_on:
      - db_mysql
    networks:
      - wpsite

  # Moodle
  moodle:
    image: bitnami/moodle:4
    container_name: "OSVH_MOODLE"
    hostname: platform.villagehosts.eu
    restart: always
    ports:
      - 8081:8080
      - 8082:8443
    env_file:
      - .env_m
    volumes:
      - ./volumes/moodle_data:/bitnami/moodle
      - ./volumes/moodledata_data:/bitnami/moodledata
    depends_on:
      - db_maria
    links:
      - db_maria
    networks:
      - msite

  # LimeSurvey
  # For user surveys
  limesurvey:
    image: docker.io/martialblog/limesurvey:latest
    container_name: "OSVH_LIMESURVEY"
    restart: always
    env_file:
      - .env_l
    volumes:
      - ./limesurvey_data:/var/www/html/upload/surveys
    ports:
      - 8085:8080
    depends_on:
      - db_postgres
    links:
      - db_postgres
    networks:
      - lsite

  # --- MANAGEMENT ---

  # Portainer
  # For managing containers
  portainer:
    image: portainer/portainer-ce:latest
    container_name: "OSVH_PORTAINER"
    hostname: platform.villagehosts.eu
    restart: always
    ports:
      - 8000:8000
      - 9443:9443
      - 9000:9000
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/portainer_data:/data
    networks:
      - wpsite
      - msite
  app:
   image: 'jc21/nginx-proxy-manager:latest'
   container_name: "OSVH_NGINXPROXYMANAGER"
   restart: always
   ports:
     - 80:80
     - 8083:81
     - 443:443
   volumes:
     - ./volumes/nginx_data:/data
     - ./volumes/letsencrypt_data:/etc/letsencrypt


volumes:
  db_mysql_data:
  db_maria_data:
  db_postgres_data:
  wp_data:
  moodle_data:
  moodledata_data:
  limesurvey_data:
  nginx_data:
  letsencrypt_data:

networks:
  wpsite:
  msite:
  lsite:
