FROM wordpress:latest

RUN apt update && \
    apt upgrade -y && \
    apt autoremove && \
    apt install -y \
    vim \
    wget \
    unzip

# Plugins to be added programmatically
# - Really Simple SSL
# - bbPress
# - BuddyPress
# - Login using WordPress Users ( WP as SAML IDP )
# - WordPress REST API – OAuth 1.0a Server
# - Complianz – GDPR/CCPA Cookie Consent
# - Matomo
# - Easy WP SMTP – WordPress Email SMTP Plugin
# - GeoDirectory
# - Image Upload for BBPress
# - Nav Menu Roles
# - Safe SVG 
# - Youzify

# Really Simple SSL
RUN wget https://downloads.wordpress.org/plugin/really-simple-ssl.6.2.0.zip
RUN unzip really-simple-ssl.6.2.0.zip
RUN cp -R really-simple-ssl /usr/src/wordpress/wp-content/plugins/really-simple-ssl
RUN rm really-simple-ssl.6.2.0.zip && rm -rf really-simple-ssl

# bbPress
RUN wget https://downloads.wordpress.org/plugin/bbpress.2.6.9.zip
RUN unzip bbpress.2.6.9.zip
RUN cp -R bbpress /usr/src/wordpress/wp-content/plugins/bbpress
RUN rm bbpress.2.6.9.zip && rm -rf bbpress

# BuddyPress
RUN wget https://downloads.wordpress.org/plugin/buddypress.11.1.0.zip
RUN unzip buddypress.11.1.0.zip
RUN cp -R buddypress /usr/src/wordpress/wp-content/plugins/buddypress
RUN rm buddypress.11.1.0.zip && rm -rf buddypress

# Login using WordPress Users ( WP as SAML IDP )
# https://plugins.miniorange.com/single-sign-on-sso-between-wordpress-as-idp-and-moodle-as-sp
RUN wget https://downloads.wordpress.org/plugin/miniorange-wp-as-saml-idp.1.14.5.zip
RUN unzip miniorange-wp-as-saml-idp.1.14.5.zip
RUN cp -R miniorange-wp-as-saml-idp /usr/src/wordpress/wp-content/plugins/miniorange-wp-as-saml-idp
RUN rm miniorange-wp-as-saml-idp.1.14.5.zip && rm -rf miniorange-wp-as-saml-idp

# WordPress REST API – OAuth 1.0a Server
RUN wget https://downloads.wordpress.org/plugin/rest-api-oauth1.0.3.0.zip
RUN unzip rest-api-oauth1.0.3.0.zip
RUN cp -R rest-api-oauth1 /usr/src/wordpress/wp-content/plugins/rest-api-oauth1
RUN rm rest-api-oauth1.0.3.0.zip && rm -rf rest-api-oauth1

# Complianz – GDPR/CCPA Cookie Consent
RUN wget https://downloads.wordpress.org/plugin/complianz-gdpr.6.4.2.zip
RUN unzip complianz-gdpr.6.4.2.zip
RUN cp -R complianz-gdpr /usr/src/wordpress/wp-content/plugins/complianz-gdpr
RUN rm complianz-gdpr.6.4.2.zip && rm -rf complianz-gdpr

# Matomo
RUN wget https://downloads.wordpress.org/plugin/matomo.4.13.5.zip
RUN unzip matomo.4.13.5.zip
RUN cp -R matomo /usr/src/wordpress/wp-content/plugins/matomo
RUN rm matomo.4.13.5.zip && rm -rf matomo

# Easy WP SMTP – WordPress Email SMTP Plugin
RUN wget https://downloads.wordpress.org/plugin/easy-wp-smtp.2.0.1.zip
RUN unzip easy-wp-smtp.2.0.1.zip
RUN cp -R easy-wp-smtp /usr/src/wordpress/wp-content/plugins/easy-wp-smtp
RUN rm easy-wp-smtp.2.0.1.zip && rm -rf easy-wp-smtp

# GeoDirectory
RUN wget https://downloads.wordpress.org/plugin/geodirectory.2.3.10.zip
RUN unzip geodirectory.2.3.10.zip
RUN cp -R geodirectory /usr/src/wordpress/wp-content/plugins/geodirectory
RUN rm geodirectory.2.3.10.zip && rm -rf geodirectory

# Image Upload for BBPress
RUN wget https://downloads.wordpress.org/plugin/image-upload-for-bbpress.1.1.18.zip
RUN unzip image-upload-for-bbpress.1.1.18.zip
RUN cp -R image-upload-for-bbpress /usr/src/wordpress/wp-content/plugins/image-upload-for-bbpress
RUN rm image-upload-for-bbpress.1.1.18.zip && rm -rf image-upload-for-bbpress

# Nav Menu Roles
RUN wget https://downloads.wordpress.org/plugin/nav-menu-roles.2.1.2.zip
RUN unzip nav-menu-roles.2.1.2.zip
RUN cp -R nav-menu-roles /usr/src/wordpress/wp-content/plugins/nav-menu-roles
RUN rm nav-menu-roles.2.1.2.zip && rm -rf nav-menu-roles

# Safe SVG
RUN wget https://downloads.wordpress.org/plugin/safe-svg.2.1.1.zip
RUN unzip safe-svg.2.1.1.zip
RUN cp -R safe-svg /usr/src/wordpress/wp-content/plugins/safe-svg
RUN rm safe-svg.2.1.1.zip && rm -rf safe-svg

# Youzify
RUN wget https://downloads.wordpress.org/plugin/youzify.1.2.2.zip
RUN unzip youzify.1.2.2.zip
RUN cp -R youzify /usr/src/wordpress/wp-content/plugins/youzify
RUN rm youzify.1.2.2.zip && rm -rf youzify

# Plugins copied manually in the folder
COPY wp-content/plugins/ /usr/src/wordpress/wp-content/plugins/

# Themes copied manually in the folder
COPY wp-content/themes/ /usr/src/wordpress/wp-content/themes/

# Uploaded files copied manually in the folder
COPY wp-content/uploads/ /usr/src/wordpress/wp-content/uploads/

# Uploads configurations
COPY ./config/uploads.ini /usr/local/etc/php/conf.d/uploads.ini
